## Importing library

In [19]:
from tensorflow.keras.preprocessing.text import one_hot

In [20]:
### sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',]


In [21]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [22]:
## Define the vocabulary size
vocab_size = 10000

In [23]:
## OOne Hot Representation
one_hot_repr = [one_hot(words, vocab_size) for words in sent]
one_hot_repr

[[7121, 3733, 7044, 3339],
 [7121, 3733, 7044, 1689],
 [7121, 5498, 7044, 2160],
 [993, 8696, 8296, 1547, 870],
 [993, 8696, 8296, 1547, 3975],
 [7607, 7121, 3273, 7044, 1146],
 [1720, 657, 1080, 1547]]

In [24]:
## Word Embedding Representation
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [25]:
import numpy as np

In [26]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7121 3733 7044 3339]
 [   0    0    0    0 7121 3733 7044 1689]
 [   0    0    0    0 7121 5498 7044 2160]
 [   0    0    0  993 8696 8296 1547  870]
 [   0    0    0  993 8696 8296 1547 3975]
 [   0    0    0 7607 7121 3273 7044 1146]
 [   0    0    0    0 1720  657 1080 1547]]


In [27]:
# Feature Representation
dim = 10

In [28]:
model = Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_length))
model.compile('adam','mse')

/home/cipher/Documents/Documents/NLP/RNN_Project/.venv/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [29]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [30]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step


array([[[-0.04929291, -0.02061393, -0.04787381, -0.00519286,
         -0.01780028,  0.04995376,  0.0177277 ,  0.0082177 ,
          0.02503575, -0.0115949 ],
        [-0.04929291, -0.02061393, -0.04787381, -0.00519286,
         -0.01780028,  0.04995376,  0.0177277 ,  0.0082177 ,
          0.02503575, -0.0115949 ],
        [-0.04929291, -0.02061393, -0.04787381, -0.00519286,
         -0.01780028,  0.04995376,  0.0177277 ,  0.0082177 ,
          0.02503575, -0.0115949 ],
        [-0.04929291, -0.02061393, -0.04787381, -0.00519286,
         -0.01780028,  0.04995376,  0.0177277 ,  0.0082177 ,
          0.02503575, -0.0115949 ],
        [ 0.02400324,  0.04795642,  0.03268666, -0.00165499,
          0.01886416, -0.00712245, -0.03549006,  0.02000383,
          0.01387012,  0.01490902],
        [ 0.03083582, -0.02743212,  0.04678715, -0.00694088,
          0.04081876, -0.04239428, -0.03737457, -0.00762345,
         -0.02077376,  0.01469612],
        [ 0.01675344,  0.0341331 , -0.02599801, -0.0